### ISSUE TITLE
Dot directory and config file not recognised

### ISSUE THREAD

**Issue by AdamLeonSmith** [fgadaleta/ncode-agent#2]
Steps:

1. Download agent
2. Run ncode-linux login

Expected result:  Prompted for credentials or failure due to credentials not in config file

Actual result:  

```
adam@adamdev:~/workspace/ncode$ ./ncode-linux login
Creating ncode home folder for the first time...
done.
No such file or directory (os error 2) (~/.ncode/configuration.toml)
Please create a configuration file under ~/.ncode/configuration.toml
```

NOTE that the directory and sample file IS created with appropriate permissions:
```
adam@adamdev:~/workspace/ncode$ ls -l ~/.ncode/
total 4
-rw-rw-r-- 1 adam adam 235 ene  6 09:22 configuration-sample.toml

```

**Comment by AdamLeonSmith** [comment]
Looking at the instructions they say "Please do copy it to configuration.toml with the correct username and password provided to you via email." - but copy it to WHERE?

**Comment by AdamLeonSmith** [comment]
Ahhh I figured it out.  It's a rename - perhaps make the instructions a bit clearer as I didn't notice the -sample.

**Comment by fgadaleta** [comment]
Exactly. Copy the sample to `configuration.toml` under the same folder. 
I am updating the `README`
