### ISSUE TITLE
Profiling throws arguments error

### ISSUE THREAD

**Issue by AdamLeonSmith** [fgadaleta/ncode-agent#3]
Attempting to profile a CSV using instructions in the README which are:

`./ncode profile --data mypath/mydata.csv --publish`

I ran:

`./ncode-linux profile --data ~/workspace/ncode/report003.csv --publish`

Expected result:  Profile and upload
Actual result:
```
adam@adamdev:~/workspace/ncode$ ./ncode-linux profile --data /home/adam/workspace/ncode/report003.csv --publish
error: Found argument '--data' which wasn't expected, or isn't valid in this context

If you tried to supply `--data` as a PATTERN use `-- --data`

USAGE:
    ncode-linux profile [FLAGS] --input <input>

For more information try --help

```

**Comment by fgadaleta** [comment]
Yes the documentation is wrong (and it has been fixed).
The correct command is `./ncode profile --input mypath/mydata.csv --publish`
